trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/src/main/asciidoc/*
      - docs/src/main/asciidoc/images/*
      - README.md
      - CONTRIBUTING.md
      - LICENSE.txt
      - dco.txt
      - .github/ISSUE_TEMPLATE/*.md

stages:
  - stage: test
    displayName: Tests
    jobs:
      - job: unit_test
        displayName: Unit tests
        strategy:
          maxParallel: 2
          matrix:
            jdk8_linux:
              imageName: 'ubuntu-16.04'
              jdk_version: '1.8'
            jdk11_linux:
              imageName: 'ubuntu-16.04'
              jdk_version: '1.11'
        pool:
          vmImage: $(imageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: verify
              jdkVersionOption: $(jdk_version)
      - job: sunat_test
        displayName: Sunat test
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: verify
              options: -Psunat