trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/src/main/asciidoc/*
      - docs/src/main/asciidoc/images/*
      - README.md
      - CONTRIBUTING.md
      - LICENSE.txt
      - dco.txt
      - .github/ISSUE_TEMPLATE/*.md

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: unit_test
        displayName: Unit tests
        strategy:
          maxParallel: 2
          matrix:
            jdk8_linux:
              imageName: 'ubuntu-16.04'
              jdk_version: '1.8'
            jdk11_linux:
              imageName: 'ubuntu-16.04'
              jdk_version: '1.11'
        pool:
          vmImage: $(imageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: verify
              jdkVersionOption: $(jdk_version)
      - job: sunat_test
        displayName: Integration tests sunat
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: verify
              options: -Psunat
  - stage: metrics
    displayName: Metrics
    jobs:
      - job: sonarCloud
        displayName: SonarCloud
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'verify'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'
          - task: SonarCloudPrepare@1
            displayName: 'Prepare SonarCloud analysis'
            inputs:
              SonarCloud: 'project-openubl/xml-builder'
              organization: 'project-openubl'
              scannerMode: 'CLI'
              configMode: 'file'
          - task: SonarCloudAnalyze@1
            displayName: 'Run SonarCloud code analysis'
            inputs:
              
          - task: SonarCloudPublish@1
            displayName: 'Publish SonarCloud quality gate results'
            inputs:
              pollingTimeoutSec: '300'
  - stage: release
    displayName: Release
    jobs:
      - job: release_java_artifacts
        displayName: Release Java artifacts
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: package
              options: -DskipTests
          - task: CopyFiles@2
            inputs:
              SourceFolder: 'target'
              Contents: '*-runner.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - job: release_to_github
        displayName: Release to Github
        dependsOn:
          - release_java_artifacts
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: GitHubRelease@1
            displayName: Create Github Release
            inputs:
              gitHubConnection: project-openubl
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'gitTag'
              assets: |
                  $(Build.ArtifactStagingDirectory)/*.jar
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
        

  